### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/topia-assignments-power-plant-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Paperwork

- [ ] No TODO markers left in group-reflection.md
- [ ] All checkboxes checked in group-reflection.md

## Control Room

- [ ] No TODO markers left in the main.py file
- [ ] main.py imports all available power sources (even if not using them)
- [ ] main.py creates function for charge_battery with complete signature
- [ ] main.py calls charge_battery with complete call
- [ ] main.py uses JSON library to read from .battery
- [ ] main.py uses JSON library to write to .battery
- [ ] main.py calls either the power or energy property

## Diversification

- [ ] Neighborhood diversified power generation to use at least one inexhaustible
- [ ] SolarField sets the wattage property of the solar panel
- [ ] WindFarm sets the turbine blade size

## Inheritance

- [ ] Inexhaustible source (SolarField) uses inheritance
- [ ] Inexhaustible source (WindFarm) uses inheritance
- [ ] Inexhaustible source (SolarField) calls the super() function to inherit
- [ ] Inexhaustible source (WindFarm) calls the super() function to inherit

## Instantiation

- [ ] Exhaustible source (OilStation) calls Oil object
- [ ] Exhaustible source (CoalStation) calls Oil object

## Methods

- [ ] Exhaustible source (OilStation) contains use method with correct signature
- [ ] Exhaustible source (CoalStation) contains use method with correct signature

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
